# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bac938b7b3727545785cd11853d3256b5cfeff5857a717938567cd9a77dc55bafefb837f4cc811d9799a1c89692478a22b1ecf4af8ab3b17948fa8d9359fd404

test:
  secret_key_base: 03e702c2ddb5d3dd3aefbd0903741e15a1d2cb83c7fc35563a8298bc8ed40aefb2cd939d190c409f4001a7a0354aa529ca7e47d215a697c2856feb73024a1953

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
